name: build/conda
run-name: ${{
    format(
      '[{0}] build/conda',
      (github.event_name == 'pull_request' && format('pr/{0}', github.event.number)) ||
      (github.event_name == 'push' && github.ref_name) ||
      (github.event_name == 'release' && github.event.release.tag_name) ||
       github.event_name
    )
  }}


on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  push:
    branches:
      - main

  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    branches:
      - main

  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]


jobs:
  build_package:
    name: Build Conda Package
    uses: energy-quants/.github/.github/workflows/build-conda.yml@main
  publish_package:
    name: Publish OCI Artifact
    needs: build_package
    runs-on: ubuntu-latest
    steps:
      - id: show_debug_info
        name: Show Debug Info
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          # Show Debug Info
          echo "::group::User Info"
          id
          echo "::endgroup::"
          echo "::group::GitHub Context"
          echo "${GITHUB_CONTEXT}"
          echo "::endgroup::"
          echo "::group::Environment Variables"
          unset GITHUB_CONTEXT
          env | sort
          echo "::endgroup::"
          echo "::group::Git Info"
          which git
          git --version
          echo "::endgroup::"

      - id: setup_micromamba
        name: Create Python Environment
        # https://github.com/mamba-org/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.4.9-0'
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
              - energy-quants
          environment-name: build
          create-args: >-
            python=3.11
            eq-devtools>=0.3.2

      - id: download_artifact
        name: Download Package
        uses: actions/download-artifact@v3
        with:
          name: conda-channel
          path: ./conda-local

      - id: publish_package
        name: Publish Package
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euox pipefail
          devtool --version
          tree ./conda-local
          for filepath in  $(find "./conda-local" -type f -name "*.conda"); do
            devtool conda publish -v --owner='energy-quants' --filepath="${filepath}"
          done