name: github/release
run-name: "[${{ github.ref_name }}] github/release"


on:
  push:
    tags:
      - '*'


permissions:
  contents: write


jobs:
  release:
    name: Create Release
    uses: energy-quants/.github/.github/workflows/create-release.yml@main
    with:
      tag: ${{ github.ref_name }}
      draft: true
