name: lint/python
run-name: ${{
    format(
      '[{0}] lint/python',
      (github.event_name == 'pull_request' && format('pr/{0}', github.event.number)) ||
      (github.event_name == 'push' && github.ref_name) ||
      (github.event_name == 'release' && github.event.release.tag_name) ||
       github.event_name
    )
  }}


on:
  pull_request:
    branches:
      - main


jobs:
  lint:
    name: Lint Python
    uses: energy-quants/.github/.github/workflows/lint-python.yml@main
