name: publish/conda
run-name: ${{
    format(
      '[{0}] publish/conda{1}',
      (github.event_name == 'pull_request' && format('pr/{0}', github.event.number)) ||
      (github.event_name == 'push' && github.ref_name) ||
      (github.event_name == 'release' && github.event.release.tag_name) ||
      github.event_name,
      (github.event.action == 'requested' && ' (requested)') || ''
    )
  }}


on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows: ['build/conda']
    types:
      - completed
      - requested


permissions:
  statuses: write


jobs:
  publish_package:
    name: Publish Conda Package
    uses: energy-quants/.github/.github/workflows/publish-conda.yml@main
    secrets:
      token: ${{ secrets.CI_PACKAGES }}
